version: '3.7'
services:
  gtas-ui:
    image: wcogtas/gtas-ui:dev
    container_name: gtas-ui
    build:
      context: .
      dockerfile: dockerfile
    ports:
#      - 80:80
      - 443:443
    restart: always
    secrets:
      - source: ui-cert
        target: /certs/gtas.crt
      - source: ui-key
        target: /certs/gtas.key
    networks:
      - gtas-webapp-network
networks:
  gtas-webapp-network:
    attachable: true
secrets:
  ui-cert:
    file: ./certs/gtas.crt
  ui-key:
    file: ./certs/gtas.key