name: GTAS UI pipeline workflow
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: gui
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@master
        name: Checkout latest code
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Clean resources
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: delete deployments --ignore-not-found=true gtas-ui
      - name: Pass backend URL
        shell: bash
        env:
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          REACT_APP_KIBANA_LOGIN: ${{ secrets.REACT_APP_KIBANA_LOGIN }}
          REACT_APP_NEO4J_BROWSER: ${{ secrets.REACT_APP_NEO4J_BROWSER }}
          REACT_APP_NEO4J: ${{ secrets.REACT_APP_NEO4J }}
        run: |
          sed -i.bak "s~REACT_APP_BASE_URL=.*~REACT_APP_BASE_URL=$REACT_APP_BASE_URL~g" .env
          sed -i.bak "s~REACT_APP_KIBANA_LOGIN=.*~REACT_APP_KIBANA_LOGIN=$REACT_APP_KIBANA_LOGIN~g" .env
          sed -i.bak "s~REACT_APP_NEO4J_BROWSER=.*~REACT_APP_NEO4J_BROWSER=$REACT_APP_NEO4J_BROWSER~g" .env
          sed -i.bak "s~REACT_APP_NEO4J=.*~REACT_APP_NEO4J=$REACT_APP_NEO4J~g" .env
      - uses: docker/build-push-action@v2
        name: Build and push GTAS UI
        with:
          repository: wcogtas/gtas-ui
          context: .
          platforms: linux/amd64
          push: true
          file: ./dockerfile
          tags: wcogtas/gtas-ui:dev
      - name: Generate Kubernetes deployment configuration file
        shell: bash
        env:
          REACT_APP_NEO4J_BROWSER: ${{ secrets.REACT_APP_NEO4J_BROWSER }}
          REACT_APP_KIBANA_LOGIN: ${{ secrets.REACT_APP_KIBANA_LOGIN }}
          REACT_APP_NEO4J: ${{ secrets.REACT_APP_NEO4J }}
        run: |
          sudo apt-get -y update
          sudo apt-get install -y curl
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.22.0/kompose-linux-amd64 -o kompose
          chmod +x kompose
          sudo mv ./kompose /usr/local/bin/kompose
          kompose -f docker-compose.yml -f k8s-pipeline-properties.yml convert -j --out deploy.json

          echo "Generating temporary sub json object with mount path"
          cat deploy.json | jq -r '.items[] | select(.kind=="Deployment" and .metadata.name=="gtas-ui") | .spec.template.spec.containers[] | select(.name=="gtas-ui") | .volumeMounts[] | select(.name=="env") | .mountPath="/usr/src/app/.env" | . += {subPath: ".env"}' > temp.json

          echo "Generating json with deleted mount path"
          cat deploy.json | jq -r 'del(.items[] | select(.kind=="Deployment" and .metadata.name=="gtas-ui")|.spec.template.spec.containers[] | select(.name=="gtas-ui") | .volumeMounts[] | select(.name=="env"))' > alt.json

          echo "Combining augmented json objects"
          jq '.items[4].spec.template.spec.containers[0].volumeMounts += [input]' alt.json temp.json > combined.json
      - name: Deploy to cluster
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f combined.json
